# # typed: false
# # frozen_string_literal: true
#
# # This file was generated by GoReleaser. DO NOT EDIT.
# class Aero < Formula
#   desc "A simple weather CLI tool!."
#   homepage "https://github.com/donwany/aero"
#   version "1.0.0"
#   bottle :unneeded
#
#   if OS.mac? && Hardware::CPU.intel?
#     url "https://github.com/donwany/aero/blob/main/aero_v0.1.1-next_Darwin_arm64.tar.gz"
#     sha256 "58213b74d682d7a6afc7ad9543f41516fde754c99e13d899bdab701b862d2be1"
#   end
#   if OS.linux? && Hardware::CPU.intel?
#     url "https://github.com/donwany/aero/blob/main/aero_v0.1.1-next_Linux_arm64.tar.gz"
#     #sha256 "ad65e443d21090c63328f5bb0ece69fd433fd9c372a91a552c878fc1b4828ace"
#   end
#
#   def install
#     bin.install "aero"
#   end
#
# #   test do
# #     assert_match /Simple port-forward wrapper tool for multiple pods/, shell_output("#{bin}/kubepfm -h", 0)
# #   end
# end

class Aero < Formula
  desc "A simple weather CLI tool!."
  homepage "https://github.com/donwany/aero"
  url "https://github.com/donwany/aero/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "58213b74d682d7a6afc7ad9543f41516fde754c99e13d899bdab701b862d2be1"

  depends_on "go"

  def install
    ENV["GOPATH"] = buildpath
    ENV["GO111MODULE"] = "on"
    ENV["GOFLAGS"] = "-mod=vendor"
    ENV["PATH"] = "#{ENV["PATH"]}:#{buildpath}/bin"
    (buildpath/"src/github.com/donwany/aero").install buildpath.children
    cd "src/github.com/donwany/aero" do
      system "go", "build", "-o", bin/"aero", "."
    end
  end

#   test do
#     assert_match /Simple port-forward wrapper tool for multiple pods/, shell_output("#{bin}/kubepfm -h", 0)
#   end
end