# # typed: false
# # frozen_string_literal: true
#
# # This file was generated by GoReleaser. DO NOT EDIT.
# class Aero < Formula
#   desc "A simple weather CLI tool!."
#   homepage "https://github.com/donwany/aero"
#   version "1.0.0"
#   bottle :unneeded
#
#   if OS.mac? && Hardware::CPU.intel?
#     url "https://github.com/donwany/aero/blob/main/aero_v0.1.1-next_Darwin_arm64.tar.gz"
#     sha256 "58213b74d682d7a6afc7ad9543f41516fde754c99e13d899bdab701b862d2be1"
#   end
#   if OS.linux? && Hardware::CPU.intel?
#     url "https://github.com/donwany/aero/blob/main/aero_v0.1.1-next_Linux_arm64.tar.gz"
#     #sha256 "ad65e443d21090c63328f5bb0ece69fd433fd9c372a91a552c878fc1b4828ace"
#   end
#
#   def install
#     bin.install "aero"
#   end
#
# #   test do
# #     assert_match /Simple port-forward wrapper tool for multiple pods/, shell_output("#{bin}/kubepfm -h", 0)
# #   end
# end

# class Program < Formula
#   desc "How to use this binary"
#   homepage "https://github.com/user/repo"
#   version "v1.2.3"
#
#   if os.Mac?
#     url "https://github.com/user/repo/releases/download/v1.2.3/program_v1.2.3_macOs_64bit.zip"
#     sha256 "9ee30fc358fae8d248a2d7538957089885da321dca3f09e3296fe2058e7fff74"
#   end
#   if OS.linux? && Hardware::CPU.intel?
#     url "https://github.com/user/repo/releases/download/v1.2.3/program_v1.2.3_Linux_64bit.zip"
#     sha256 "b41bebd25fd7bb1a67dc2cd5ee12c9f67073094567fdf7b3871f05fd74a45fdd"
#   end
#   if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
#     url "https://github.com/user/repo/releases/download/v1.2.3/program_v1.2.3_Linux_armv7.zip"
#     sha256 "78f31239430eaaec01df783e2a3443753a8126c325292ed8ddb1658ddd2b401d"
#   end
#   if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
#     url "https://github.com/user/repo/releases/download/v1.2.3/program_v1.2.3_Linux_arm64.zip"
#     sha256 "97cadca3c3c3f36388a4a601acf878dd356d6275a976bee516798b72bfdbeecf"
#   end
#
#   depends_on "git"
#   depends_on "zsh" => :optional
#
#   def install
#     bin.install "program"
#   end
#
#   def post_install
#     etc.install "app-config.conf"
#   end
# end


class Aero < Formula
  desc "A simple weather CLI tool!."
  homepage "https://github.com/donwany/aero"
  url "https://github.com/donwany/aero/archive/refs/tags/v1.0.0.tar.gz"
  sha256  "530f342a5ce35ca0748c7d6538181f815f945ec998ee2cda14e77df3e3637ce1"

  depends_on "go"

  def install
    ENV["GOPATH"] = buildpath
    ENV["GO111MODULE"] = "on"
    ENV["GOFLAGS"] = "-mod=readonly"
    ENV["PATH"] = "#{ENV["PATH"]}:#{buildpath}/bin"
    (buildpath/"src/github.com/donwany/aero").install buildpath.children
    cd "src/github.com/donwany/aero" do
      system "go", "build", "-o", bin/"aero", "."
    end
  end

#   test do
#     assert_match /Simple port-forward wrapper tool for multiple pods/, shell_output("#{bin}/kubepfm -h", 0)
#   end
end